### ISSUE TITLE
Does it support on-premises TFS?

### ISSUE THREAD

**Issue by gyoreg** [ostreifel/vsts-rest-multivalue#1]
Does it support on-premises TFS? Which versions? How can I configure it (as with on-premise I have only the xml-based WIT definition)?

**Comment by ostreifel** [comment]
With the on premise installation export the wit and goto

/WITD/WORKITEMTYPE/FORM/WebLayout/Extensions
add
```xml
<Extension Id="ottostreifel.vsts-rest-multivalue-control" />
```

within the same layout goto the group you would like to add the control to and add
```xml
<ControlContribution Id="ottostreifel.vsts-rest-multivalue-control.multivalue-form-control" Label="Rest Multivalue control">
   <Inputs>
      <Input Id="FieldName" Value="SomeFieldName" />
      <Input Id="Url" Value="SomeUrl" />
      <Input Id="Property" Value="Optionally specify a property" />
   </Inputs>
</ControlContribution>
```

**Comment by ostreifel** [comment]
That's for installations that support the [new work item form](https://www.visualstudio.com/en-us/docs/work/process/new-work-item-experience)
