### ISSUE TITLE
Support jsonpath for the property to use

### ISSUE THREAD

**Issue by jessehouwing** [ostreifel/vsts-rest-multivalue#2]
Example:

URL: `http://api.fbi.gov/wanted`
Property: `$.items[*].title`

Should return:

```
[
  "TYRONE SMITH",
  "DANIEL ANDREAS SAN DIEGO",
  "FAUSTO ISIDRO MEZA-FLORES",
  "MURDER VICTIMS",
  "MAURO OCIEL VALENZUELA-REYES",
  "RACHEL LOUISE COOKE",
  "DEXTER O'NEIL BANKS",
  "UNKNOWN SUSPECT",
  "SANTIAGO VILLALBA MEDEROS",
  "MARCUS EDWARDS",
  "KEVIN ROBERT HARRIS II",
  "LAMONT STEPHENSON",
  "ASHA JAQUILLA DEGREE",
  "RYAN BRABEN CHICOVSKY",
  "JOHN DOE - WHITE SANDS, NEW MEXICO",
  "ERIC BILLS",
  "ASHLEY SUMMERS",
  "TRIPLE HOMICIDE INVESTIGATION",
  "LUIS MACEDO",
  "JULIO CESAR GUEVARA-MEJIA"
]
```

That makes the control a lot more flexible if I (in many cases) do not have control over the REST API being called.

**Comment by whschultz** [comment]
Without something like this, how would we get a list of the [areas in VSTS](https://www.visualstudio.com/en-us/docs/integrate/api/wit/classification-nodes)?

**Comment by ostreifel** [comment]
Updated to use json path when property starts w/ '$'

Sorry for slow response time - I forgot to mark this repository as watched when I created it.
