### ISSUE TITLE
How to use for TFS On Premises 

### ISSUE THREAD

**Issue by pmauri01** [ostreifel/vsts-rest-multivalue#3]
How can I use this extension for TFS2017 On Premises?
I don't see the "Process" tab

![tfs 2017 menu](https://user-images.githubusercontent.com/35079822/34539486-dd18878e-f08d-11e7-9074-7b3ad1850c02.png)

**Comment by ostreifel** [comment]
Added [instructions](https://marketplace.visualstudio.com/items?itemName=ottostreifel.vsts-rest-multivalue-control#user-content-on-premises) to store page.

In addition to above, if you are just starting out you will need to goto ProcessTemplate.xml ProcessTemplate/version make a change to guid to make it distinct from the system process

Sorry for slow response, I had initially forgot to turn on notifications when I created this repository.
