### ISSUE TITLE
Devops Blank Field

### ISSUE THREAD

**Issue by dairuin** [ostreifel/vsts-rest-multivalue#7]
Hello,
i' ve configured the custom control like in example but i see only blank field

![image](https://user-images.githubusercontent.com/20791600/74327229-14538700-4d8c-11ea-9a46-af778e1a8128.png)

can you help me ?

**Comment by maurizioprazzoli** [comment]
Hi, I'd like to suggest to check the detail of the error; checking out your browser using DevTools and Inspect Network Activity, to find out if there are any errors in comminication and detect request/response details.

Ensure to have correctly configured CORS on target function service
