### ISSUE TITLE
Unable to configure an URL from another site

### ISSUE THREAD

**Issue by jjslagace** [ostreifel/vsts-rest-multivalue#9]
Hi,

This is for an On Premise scenario.

I'm trying to bind the REST MultiValue control to an URL not under our TFS site and I'm getting CORS errors in the console:

![CORS-Error](https://user-images.githubusercontent.com/2769697/138715103-c0ab78ae-a8df-4dc3-b2fa-2d9132198335.png)

I'm no CORS expert but I can see in the request detail, the origin is "null" witch I think is the cause for the CORS preflight request to fail:

![CORS-Error2](https://user-images.githubusercontent.com/2769697/138716132-e440b6df-e4e1-45c8-adfb-ae7232375273.png)

Do you have any recommandation or work around for this scenario?

Thanks

Stéphane

**Comment by MatthewDiPietroTR** [comment]
Same question--does this only work for ADO APIs or can an external API be used? For instance, we have a request to be able to track the customer who requested a feature, and want to maintain standards so that completed features can be communicated to the source. Would we be able to use this control to point to an API end point that lists our customers?

**Comment by jjslagace** [comment]
I checked the iframe rendering in HTML and it is using the sandbox attribute with the following options:
allow-downloads_ allow-forms allow-modals allow-pointer-lock allow-popups allow-scripts allow-top-navigation

The "allow-same-origin" option is not there but I'm not shure if that is the blocker.

**Comment by jjslagace** [comment]
Finaly I was able to setup the CORS headers to allow requests to my data service.

In my case the required response headers in the service were the following:
  Access-Control-Allow-Credentials:true
  Access-Control-Allow-Headers:Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access- 
 Control-Request-Headers, authorization
  Access-Control-Allow-Methods:GET,HEAD,OPTIONS,POST,PUT
  Access-Control-Allow-Origin:null
